const API='https://mantledb.sh/v2/peterslab-mibang-89b8f9bc/campaign-state';
let DEFAULT_STATE=null;
const I={
ko:{sub:'푸들 건강검진 캠페인 운영',owner:'담당자 · Mibang',title:'푸들 캠페인 일일 운영 대시보드',desc:'7월 29일 티저부터 8월 15일 접수 마감까지 Mibang 업무만 관리합니다.',hours:'근무시간',period:'접수기간',post:'일일 콘텐츠',dmgoal:'일일 DM',today:'오늘의 업무',calendar:'캘린더',content:'콘텐츠 기획',dmlist:'DM 리스트',data:'데이터 관리',routine:'일일 루틴',r1:'문의·신청 확인',r2:'푸들 보호자 탐색',r3:'DM 30명 분산 발송',r4:'콘텐츠 제작·게시',r5:'답장·댓글 대응',r6:'일일 마감 기록',todayplan:'선택일 콘텐츠',add:'DM 후보 추가',dog:'푸들 이름',residence:'일본 거주 확인 근거',memo:'메모',save:'저장',finish:'오늘 업무 마감 저장',edit:'수정',delete:'삭제',calHelp:'날짜별 할 일을 수정하면 오늘의 업무에도 반영됩니다.',contentHelp:'제목과 기획 내용을 수정하고 저장할 수 있습니다.',cloudStatus:'클라우드 상태',lastSaved:'마지막 저장',recordCount:'저장 데이터',reload:'클라우드 새로고침',export:'백업 다운로드',import:'백업 불러오기',editPlan:'일정·콘텐츠 수정',close:'닫기',date:'날짜',saveChanges:'수정내용 저장',cancel:'취소',loading:'클라우드 데이터 불러오는 중',online:'클라우드 연결됨',offline:'클라우드 연결 실패·이 기기에 임시 저장',saving:'클라우드 저장 중',saved:'클라우드 저장 완료',saveFail:'클라우드 저장 실패·이 기기에 임시 저장',noData:'등록된 데이터가 없습니다.',duplicate:'이미 등록된 계정입니다.',statuses:{not_sent:'미발송',sent:'발송 완료',replied:'답장 있음',interested:'관심 있음',link_sent:'링크 전달',applied:'신청 완료',excluded:'대상 제외',declined:'거절'}},
ja:{sub:'プードル健康チェックキャンペーン運営',owner:'担当者 · Mibang',title:'プードルキャンペーン運営ダッシュボード',desc:'7月29日のティザーから8月15日の受付終了まで、Mibangの業務のみを管理します。',hours:'勤務時間',period:'受付期間',post:'デイリー投稿',dmgoal:'1日DM',today:'今日の業務',calendar:'カレンダー',content:'投稿企画',dmlist:'DMリスト',data:'データ管理',routine:'日次ルーティン',r1:'問い合わせ・申込確認',r2:'プードル飼い主を検索',r3:'DM30件を分散送信',r4:'投稿制作・公開',r5:'返信・コメント対応',r6:'日次締め記録',todayplan:'選択日の投稿企画',add:'DM候補を追加',dog:'プードル名',residence:'日本在住の確認根拠',memo:'メモ',save:'保存',finish:'今日の業務締めを保存',edit:'編集',delete:'削除',calHelp:'日付ごとの業務を編集すると「今日の業務」にも反映されます。',contentHelp:'タイトルと企画内容を編集して保存できます。',cloudStatus:'クラウド状態',lastSaved:'最終保存',recordCount:'保存データ',reload:'クラウド再読込',export:'バックアップ保存',import:'バックアップ読込',editPlan:'スケジュール・投稿企画を編集',close:'閉じる',date:'日付',saveChanges:'変更内容を保存',cancel:'キャンセル',loading:'クラウドデータを読込中',online:'クラウド接続済み',offline:'クラウド接続失敗・この端末に一時保存',saving:'クラウドへ保存中',saved:'クラウド保存完了',saveFail:'クラウド保存失敗・この端末に一時保存',noData:'データがありません。',duplicate:'すでに登録済みのアカウントです。',statuses:{not_sent:'未送信',sent:'送信済み',replied:'返信あり',interested:'関心あり',link_sent:'リンク送付',applied:'申込完了',excluded:'対象外',declined:'辞退'}}};
let lang=localStorage.getItem('mibang_lang')||'ko';
let selected='';
let state=null,saveTimer=null,saveChain=Promise.resolve(),cloudOk=false;
const $=id=>document.getElementById(id),clone=o=>JSON.parse(JSON.stringify(o)),todayISO=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Asia/Tokyo'}),esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function mergeState(remote){const x=remote&&typeof remote==='object'?remote:{};const plans=Array.isArray(x.plans)&&x.plans.length?x.plans:clone(DEFAULT_STATE.plans);return{version:2,updatedAt:x.updatedAt||new Date().toISOString(),dmList:Array.isArray(x.dmList)?x.dmList:[],checks:x.checks&&typeof x.checks==='object'?x.checks:{},dailyLogs:Array.isArray(x.dailyLogs)?x.dailyLogs:[],plans};}
function migrateLocal(){try{const dm=JSON.parse(localStorage.getItem('mibang_dm')||'[]'),checks=JSON.parse(localStorage.getItem('mibang_checks')||'{}');if(dm.length)state.dmList=dm;if(Object.keys(checks).length)state.checks=checks}catch(e){}}
function saveLocal(){localStorage.setItem('mibang_cloud_backup',JSON.stringify(state));}
function status(kind,text){const dot=$('heroDot');dot.className='status-dot'+(kind==='ok'?' ok':kind==='bad'?' bad':'');$('heroStatus').textContent=text;$('cloudStatusText').textContent=text;cloudOk=kind==='ok';}
async function loadCloud(force=false){status('',I[lang].loading);try{const r=await fetch(API,{cache:'no-store'});if(r.ok){state=mergeState(await r.json());saveLocal();status('ok',I[lang].online);renderAll();return true}if(r.status!==404)throw new Error('HTTP '+r.status);migrateLocal();await writeCloud();renderAll();return true}catch(e){const local=localStorage.getItem('mibang_cloud_backup');if(local&&!force){try{state=mergeState(JSON.parse(local))}catch(_){migrateLocal()}}else migrateLocal();saveLocal();status('bad',I[lang].offline);renderAll();return false}}
function queueSave(target='taskSync'){clearTimeout(saveTimer);const box=$(target);if(box)box.textContent=I[lang].saving;saveTimer=setTimeout(()=>{saveChain=saveChain.then(()=>writeCloud(target))},400)}
async function writeCloud(target){state.updatedAt=new Date().toISOString();saveLocal();const box=target?$(target):null;if(box)box.textContent=I[lang].saving;try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!r.ok)throw new Error('HTTP '+r.status);status('ok',I[lang].online);if(box)box.textContent=I[lang].saved+' · '+new Date().toLocaleTimeString();renderData();return true}catch(e){status('bad',I[lang].offline);if(box)box.textContent=I[lang].saveFail;return false}}
function statusOptions(v='not_sent'){return Object.entries(I[lang].statuses).map(([k,n])=>`<option value="${k}" ${k===v?'selected':''}>${n}</option>`).join('')}
function planFor(d=selected){return state.plans.find(p=>p.date===d)}
function tasksFor(p){const raw=lang==='ja'?p?.tasksJa:p?.tasksKo;return String(raw||'').split('\n').map(x=>x.trim()).filter(Boolean)}
function setLang(x){lang=x;localStorage.setItem('mibang_lang',x);$('ko').classList.toggle('on',x==='ko');$('ja').classList.toggle('on',x==='ja');document.querySelectorAll('[data-i]').forEach(e=>{const k=e.dataset.i;if(I[x][k])e.textContent=I[x][k]});document.querySelectorAll('[data-ph]').forEach(e=>e.placeholder=I[x][e.dataset.ph]);$('status').innerHTML=statusOptions();renderAll()}
function renderTasks(){const p=planFor();$('todayTitle').textContent=selected;const tasks=tasksFor(p),done=state.checks[selected]||[];$('checks').innerHTML=tasks.map((t,i)=>`<label><input type="checkbox" data-task="${i}" ${done[i]?'checked':''}>${esc(t)}</label>`).join('')||`<div class="empty">${I[lang].noData}</div>`;$('checks').querySelectorAll('input').forEach(el=>el.onchange=()=>{state.checks[selected]=state.checks[selected]||[];state.checks[selected][+el.dataset.task]=el.checked;saveLocal();queueSave('taskSync')});$('taskSync').textContent=cloudOk?I[lang].saved:I[lang].offline;$('plan').innerHTML=p?`<span class="pill">${esc(p.date)}</span><h3>${esc(lang==='ja'?p.titleJa:p.titleKo)}</h3><p>${esc(lang==='ja'?p.detailJa:p.detailKo)}</p>`:''}
function renderCalendar(){$('calendarGrid').innerHTML=state.plans.map(p=>`<div class="day ${p.date===selected?'on':''}"><small>${esc(p.date)}</small><h4>${esc(lang==='ja'?p.titleJa:p.titleKo)}</h4><p class="muted">${tasksFor(p).length} tasks</p><div class="actions"><button class="btn alt small open-date" data-date="${p.date}">${I[lang].edit}</button><button class="btn small select-date" data-date="${p.date}">${I[lang].today}</button></div></div>`).join('');document.querySelectorAll('.open-date').forEach(b=>b.onclick=()=>openEditor(b.dataset.date));document.querySelectorAll('.select-date').forEach(b=>b.onclick=()=>{selected=b.dataset.date;localStorage.setItem('mibang_date',selected);document.querySelector('[data-tab="today"]').click();renderAll()})}
function renderContents(){$('contentGrid').innerHTML=state.plans.map(p=>`<div class="card content-card"><small>${esc(p.date)}</small><h3>${esc(lang==='ja'?p.titleJa:p.titleKo)}</h3><p>${esc(lang==='ja'?p.detailJa:p.detailKo)}</p><div class="actions"><button class="btn alt small edit-content" data-date="${p.date}">${I[lang].edit}</button></div></div>`).join('');document.querySelectorAll('.edit-content').forEach(b=>b.onclick=()=>openEditor(b.dataset.date))}
function renderDM(){const t=todayISO();$('sentToday').textContent=state.dmList.filter(x=>x.sent===t).length;$('dmBody').innerHTML=state.dmList.length?state.dmList.map((x,i)=>`<tr><td><b>${esc(x.account)}</b><br>${x.url?`<a href="${esc(x.url)}" target="_blank">open</a>`:''}</td><td>${esc(x.dog)}</td><td>${esc(x.residence)}</td><td><input class="input dmdate" data-i2="${i}" type="date" value="${esc(x.sent)}"></td><td><select class="dmstatus" data-i2="${i}">${statusOptions(x.status)}</select></td><td>${esc(x.note)}</td><td><button class="btn danger small del" data-i2="${i}">${I[lang].delete}</button></td></tr>`).join(''):`<tr><td colspan="7" class="empty">${I[lang].noData}</td></tr>`;document.querySelectorAll('.dmdate').forEach(e=>e.onchange=()=>{state.dmList[+e.dataset.i2].sent=e.value;queueSave('dmSync');renderDM()});document.querySelectorAll('.dmstatus').forEach(e=>e.onchange=()=>{state.dmList[+e.dataset.i2].status=e.value;queueSave('dmSync')});document.querySelectorAll('.del').forEach(e=>e.onclick=()=>{state.dmList.splice(+e.dataset.i2,1);renderDM();queueSave('dmSync')});$('dmSync').textContent=cloudOk?I[lang].saved:I[lang].offline}
function renderData(){$('lastSavedText').textContent=state.updatedAt?new Date(state.updatedAt).toLocaleString():'-';$('recordCountText').textContent=`DM ${state.dmList.length} · Plans ${state.plans.length} · Logs ${state.dailyLogs.length}`;$('dataMsg').textContent=cloudOk?I[lang].online:I[lang].offline;$('dataMsg').className='sync '+(cloudOk?'ok':'bad')}
function renderAll(){renderTasks();renderCalendar();renderContents();renderDM();renderData()}
function openEditor(date){const p=planFor(date);if(!p)return;$('editDate').value=p.date;$('editTitleKo').value=p.titleKo||'';$('editTitleJa').value=p.titleJa||'';$('editDetailKo').value=p.detailKo||'';$('editDetailJa').value=p.detailJa||'';$('editTasksKo').value=p.tasksKo||'';$('editTasksJa').value=p.tasksJa||'';$('planSaveMsg').textContent='';$('editModal').classList.add('on')}
function closeEditor(){$('editModal').classList.remove('on')}
$('savePlan').onclick=async()=>{const p=planFor($('editDate').value);if(!p)return;Object.assign(p,{titleKo:$('editTitleKo').value.trim(),titleJa:$('editTitleJa').value.trim(),detailKo:$('editDetailKo').value.trim(),detailJa:$('editDetailJa').value.trim(),tasksKo:$('editTasksKo').value.trim(),tasksJa:$('editTasksJa').value.trim()});$('planSaveMsg').textContent=I[lang].saving;const ok=await writeCloud('planSaveMsg');if(ok){renderAll();setTimeout(closeEditor,250)}};
$('closeModal').onclick=$('cancelPlan').onclick=closeEditor;$('editModal').onclick=e=>{if(e.target===$('editModal'))closeEditor()};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('on'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');$(b.dataset.tab).classList.add('on')});
$('dmForm').onsubmit=async e=>{e.preventDefault();const account=$('account').value.trim();if(state.dmList.some(x=>String(x.account).toLowerCase()===account.toLowerCase())){alert(I[lang].duplicate);return}state.dmList.push({id:crypto.randomUUID(),account,dog:$('dog').value.trim(),url:$('url').value.trim(),residence:$('residence').value.trim(),found:$('found').value,sent:$('sent').value,status:$('status').value,follow:$('follow').value,note:$('note').value.trim(),updatedAt:new Date().toISOString()});e.target.reset();$('status').innerHTML=statusOptions();$('found').value=todayISO();$('sent').value=todayISO();renderDM();await writeCloud('dmSync')};
$('finishDay').onclick=async()=>{const p=planFor();state.dailyLogs.push({id:crypto.randomUUID(),date:selected,completedAt:new Date().toISOString(),completed:(state.checks[selected]||[]).filter(Boolean).length,total:tasksFor(p).length,dmCount:state.dmList.filter(x=>x.sent===selected).length});await writeCloud('taskSync')};$('editToday').onclick=()=>openEditor(selected);
$('reloadCloud').onclick=async()=>{await loadCloud(true);$('dataMsg').textContent=cloudOk?I[lang].online:I[lang].offline};
$('exportData').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mibang-backup-${todayISO()}.json`;a.click();URL.revokeObjectURL(a.href)};
$('importData').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=async()=>{try{state=mergeState(JSON.parse(rd.result));renderAll();await writeCloud('dataMsg')}catch(err){$('dataMsg').textContent='Invalid backup file'}};rd.readAsText(f)};
$('ko').onclick=()=>setLang('ko');$('ja').onclick=()=>setLang('ja');async function boot(){DEFAULT_STATE=await fetch('defaults.json',{cache:'no-store'}).then(r=>r.json());selected=localStorage.getItem('mibang_date')||DEFAULT_STATE.plans[0].date;state=clone(DEFAULT_STATE);$('found').value=todayISO();$('sent').value=todayISO();setLang(lang);await loadCloud()}boot();